apiVersion: 1

datasources:
  - name: AssetDashboardAPI
    type: yesoreyeram-infinity-datasource
    uid: PD043CF1CCE24D2D7
    access: proxy
    url: http://api:8000
    isDefault: true
    jsonData:
      tlsSkipVerify: true
      allowedHosts:
        - http://api:8000
    editable: true
